// Seed finance summary — generated by running the live pipeline
// (categorise.js → financeStats.js) over Arin's real Revolut export
// (2025-10-01 → 2026-04-18, 1,413 transactions). This is the SAME code path as
// an in-app CSV import, so the default view matches what an import produces.
// Regenerate from a newer export with the same pipeline.

export const FINANCE_SEED = {
  "seeded": true,
  "rangeLabel": "Oct 25 – Apr 26 · 6 mo",
  "range": {
    "start": "2025-10-01",
    "end": "2026-04-18",
    "months": [
      "2025-10",
      "2025-11",
      "2025-12",
      "2026-01",
      "2026-02",
      "2026-03",
      "2026-04"
    ],
    "days": 199
  },
  "stats": {
    "income": {
      "perMonth": 9086,
      "perWeek": 2097,
      "note": "BODDY + Unify (invoiced)"
    },
    "cardSpend": {
      "perMonth": 2782,
      "perWeek": 642,
      "note": "transfers excl."
    },
    "rentNet": {
      "perMonth": -87,
      "perWeek": -20,
      "gross": 1500,
      "offset": 1587,
      "note": "€1,500 − €1,587 Dan"
    },
    "net": {
      "perMonth": 6391,
      "perWeek": 1475,
      "note": "before P2P paybacks"
    }
  },
  "deductible": {
    "perMonth": 486,
    "perWeek": 112
  },
  "excluded": {
    "perMonth": 6312,
    "total": 41265
  },
  "categories": [
    {
      "key": "eating_out",
      "label": "Eating out",
      "total": 5014,
      "count": 287,
      "perMonth": 767,
      "perWeek": 176,
      "perDay": 25.2,
      "deductible": 0,
      "business": false,
      "spark": [
        1,
        0.8672317377694928,
        0.9789505152463684,
        0.6465902296627158,
        0.006260331305173563,
        0.5983188548517565,
        0.31145148243238474
      ],
      "monthly": [
        1137,
        986,
        1113,
        735,
        7,
        680,
        354
      ],
      "merchants": [
        {
          "name": "Glovo",
          "domain": "glovoapp.com",
          "total": 1456,
          "count": 74,
          "perMonth": 223,
          "perWeek": 51,
          "perDay": 7.3
        },
        {
          "name": "Honest Greens",
          "domain": "honestgreens.com",
          "total": 825,
          "count": 86,
          "perMonth": 126,
          "perWeek": 29,
          "perDay": 4.1
        },
        {
          "name": "Norrsken Foundation",
          "domain": "norrsken.org",
          "total": 283,
          "count": 4,
          "perMonth": 43,
          "perWeek": 10,
          "perDay": 1.4
        },
        {
          "name": "Taberna Gouda",
          "domain": null,
          "total": 195,
          "count": 1,
          "perMonth": 30,
          "perWeek": 7,
          "perDay": 1
        },
        {
          "name": "Phoshfood.com*marbella",
          "domain": null,
          "total": 190,
          "count": 2,
          "perMonth": 29,
          "perWeek": 7,
          "perDay": 1
        },
        {
          "name": "Ramses",
          "domain": null,
          "total": 147,
          "count": 1,
          "perMonth": 22,
          "perWeek": 5,
          "perDay": 0.7
        },
        {
          "name": "Guitart La Molina",
          "domain": null,
          "total": 109,
          "count": 2,
          "perMonth": 17,
          "perWeek": 4,
          "perDay": 0.5
        },
        {
          "name": "La Principal",
          "domain": null,
          "total": 106,
          "count": 1,
          "perMonth": 16,
          "perWeek": 4,
          "perDay": 0.5
        }
      ],
      "extra": {
        "count": 59,
        "perMonth": 259
      }
    },
    {
      "key": "software_biz",
      "label": "Business tools",
      "total": 3178,
      "count": 70,
      "perMonth": 486,
      "perWeek": 112,
      "perDay": 16,
      "deductible": 486,
      "business": true,
      "spark": [
        1,
        0.7383735063672233,
        0.7381865100884494,
        0.1684836471754212,
        0.06497185706004452,
        0.2580829141500084,
        0.003272434878545917
      ],
      "monthly": [
        1070,
        790,
        790,
        180,
        69,
        276,
        4
      ],
      "merchants": [
        {
          "name": "Highlevel",
          "domain": "gohighlevel.com",
          "total": 1506,
          "count": 12,
          "perMonth": 230,
          "perWeek": 53,
          "perDay": 7.6
        },
        {
          "name": "Clickup.com",
          "domain": "clickup.com",
          "total": 445,
          "count": 3,
          "perMonth": 68,
          "perWeek": 16,
          "perDay": 2.2
        },
        {
          "name": "Connectcentre.ie",
          "domain": null,
          "total": 313,
          "count": 4,
          "perMonth": 48,
          "perWeek": 11,
          "perDay": 1.6
        },
        {
          "name": "Weicheng1",
          "domain": null,
          "total": 232,
          "count": 1,
          "perMonth": 35,
          "perWeek": 8,
          "perDay": 1.2
        },
        {
          "name": "Openai",
          "domain": "openai.com",
          "total": 99,
          "count": 6,
          "perMonth": 15,
          "perWeek": 3,
          "perDay": 0.5
        },
        {
          "name": "Hostinger",
          "domain": null,
          "total": 63,
          "count": 3,
          "perMonth": 10,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Make",
          "domain": null,
          "total": 58,
          "count": 7,
          "perMonth": 9,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Zapier",
          "domain": "zapier.com",
          "total": 56,
          "count": 2,
          "perMonth": 9,
          "perWeek": 2,
          "perDay": 0.3
        }
      ],
      "extra": {
        "count": 14,
        "perMonth": 61
      }
    },
    {
      "key": "shopping",
      "label": "Shopping",
      "total": 2436,
      "count": 41,
      "perMonth": 373,
      "perWeek": 86,
      "perDay": 12.2,
      "deductible": 0,
      "business": false,
      "spark": [
        0.09875468313017785,
        0.567898791620495,
        0.3884359664397657,
        1,
        0.391021581974566,
        0.6396760065431905,
        0.12790881747665034
      ],
      "monthly": [
        75,
        430,
        294,
        758,
        296,
        485,
        97
      ],
      "merchants": [
        {
          "name": "Amazon",
          "domain": "amazon.com",
          "total": 669,
          "count": 17,
          "perMonth": 102,
          "perWeek": 24,
          "perDay": 3.4
        },
        {
          "name": "Sp Tern Setups",
          "domain": null,
          "total": 449,
          "count": 1,
          "perMonth": 69,
          "perWeek": 16,
          "perDay": 2.3
        },
        {
          "name": "Temu",
          "domain": "temu.com",
          "total": 241,
          "count": 2,
          "perMonth": 37,
          "perWeek": 8,
          "perDay": 1.2
        },
        {
          "name": "Amevista",
          "domain": null,
          "total": 191,
          "count": 1,
          "perMonth": 29,
          "perWeek": 7,
          "perDay": 1
        },
        {
          "name": "Cash Withdrawal At Perfumeria Passion",
          "domain": null,
          "total": 126,
          "count": 1,
          "perMonth": 19,
          "perWeek": 4,
          "perDay": 0.6
        },
        {
          "name": "Nespresso",
          "domain": "nespresso.com",
          "total": 120,
          "count": 6,
          "perMonth": 18,
          "perWeek": 4,
          "perDay": 0.6
        },
        {
          "name": "Vanquish Fitness",
          "domain": null,
          "total": 104,
          "count": 1,
          "perMonth": 16,
          "perWeek": 4,
          "perDay": 0.5
        },
        {
          "name": "Nike",
          "domain": "nike.com",
          "total": 96,
          "count": 1,
          "perMonth": 15,
          "perWeek": 3,
          "perDay": 0.5
        }
      ],
      "extra": {
        "count": 10,
        "perMonth": 68
      }
    },
    {
      "key": "p2p_out",
      "label": "Sent to people",
      "total": 2399,
      "count": 31,
      "perMonth": 367,
      "perWeek": 84,
      "perDay": 12.1,
      "deductible": 0,
      "business": false,
      "spark": [
        0.4231846153846154,
        0.9492307692307692,
        0.6684615384615384,
        0.2230769230769231,
        0.07663076923076924,
        1,
        0.3507692307692308
      ],
      "monthly": [
        275,
        617,
        435,
        145,
        50,
        650,
        228
      ],
      "merchants": [
        {
          "name": "Lisette Hoepelman",
          "domain": null,
          "total": 844,
          "count": 8,
          "perMonth": 129,
          "perWeek": 30,
          "perDay": 4.2
        },
        {
          "name": "Benjamin Wacker",
          "domain": null,
          "total": 500,
          "count": 1,
          "perMonth": 76,
          "perWeek": 18,
          "perDay": 2.5
        },
        {
          "name": "Ana Luisa Uran Grajales",
          "domain": null,
          "total": 242,
          "count": 5,
          "perMonth": 37,
          "perWeek": 9,
          "perDay": 1.2
        },
        {
          "name": "Luisa Fernanda Rodriguez Bedoya",
          "domain": null,
          "total": 156,
          "count": 3,
          "perMonth": 24,
          "perWeek": 5,
          "perDay": 0.8
        },
        {
          "name": "Hony Moazzam",
          "domain": null,
          "total": 120,
          "count": 1,
          "perMonth": 18,
          "perWeek": 4,
          "perDay": 0.6
        },
        {
          "name": "Andrew Swailes",
          "domain": null,
          "total": 115,
          "count": 1,
          "perMonth": 18,
          "perWeek": 4,
          "perDay": 0.6
        },
        {
          "name": "Steven Wise",
          "domain": null,
          "total": 92,
          "count": 1,
          "perMonth": 14,
          "perWeek": 3,
          "perDay": 0.5
        },
        {
          "name": "Arin Ibrisim-melvin",
          "domain": null,
          "total": 69,
          "count": 1,
          "perMonth": 11,
          "perWeek": 2,
          "perDay": 0.3
        }
      ],
      "extra": {
        "count": 6,
        "perMonth": 41
      }
    },
    {
      "key": "travel",
      "label": "Travel",
      "total": 1970,
      "count": 21,
      "perMonth": 301,
      "perWeek": 69,
      "perDay": 9.9,
      "deductible": 0,
      "business": false,
      "spark": [
        0.01479746770291832,
        0.13111843121107625,
        1,
        0.6219697359617069,
        0.6106078542385096,
        0.14461629522878175,
        0.011580626897936076
      ],
      "monthly": [
        12,
        102,
        777,
        483,
        475,
        112,
        9
      ],
      "merchants": [
        {
          "name": "Airbnb",
          "domain": "airbnb.com",
          "total": 442,
          "count": 1,
          "perMonth": 68,
          "perWeek": 16,
          "perDay": 2.2
        },
        {
          "name": "Hotel Costa Rica",
          "domain": null,
          "total": 314,
          "count": 1,
          "perMonth": 48,
          "perWeek": 11,
          "perDay": 1.6
        },
        {
          "name": "Stoketravel",
          "domain": null,
          "total": 255,
          "count": 1,
          "perMonth": 39,
          "perWeek": 9,
          "perDay": 1.3
        },
        {
          "name": "Enterticket",
          "domain": null,
          "total": 230,
          "count": 2,
          "perMonth": 35,
          "perWeek": 8,
          "perDay": 1.2
        },
        {
          "name": "World Duty Free",
          "domain": null,
          "total": 200,
          "count": 2,
          "perMonth": 31,
          "perWeek": 7,
          "perDay": 1
        },
        {
          "name": "Iberia",
          "domain": null,
          "total": 184,
          "count": 2,
          "perMonth": 28,
          "perWeek": 6,
          "perDay": 0.9
        },
        {
          "name": "Trip.com",
          "domain": null,
          "total": 86,
          "count": 1,
          "perMonth": 13,
          "perWeek": 3,
          "perDay": 0.4
        },
        {
          "name": "Agoda",
          "domain": "agoda.com",
          "total": 79,
          "count": 1,
          "perMonth": 12,
          "perWeek": 3,
          "perDay": 0.4
        }
      ],
      "extra": {
        "count": 6,
        "perMonth": 27
      }
    },
    {
      "key": "other",
      "label": "Other",
      "total": 1103,
      "count": 81,
      "perMonth": 169,
      "perWeek": 39,
      "perDay": 5.5,
      "deductible": 0,
      "business": false,
      "spark": [
        0.23297233633047024,
        0.5092355864525581,
        0.41868949469995115,
        0.3109074717761627,
        1,
        0.5860503863721237,
        0.1107408577748413
      ],
      "monthly": [
        81,
        177,
        146,
        108,
        348,
        204,
        39
      ],
      "merchants": [
        {
          "name": "Mercado Pago",
          "domain": null,
          "total": 204,
          "count": 1,
          "perMonth": 31,
          "perWeek": 7,
          "perDay": 1
        },
        {
          "name": "Merpago Republica",
          "domain": null,
          "total": 49,
          "count": 1,
          "perMonth": 8,
          "perWeek": 2,
          "perDay": 0.2
        },
        {
          "name": "Belladona",
          "domain": null,
          "total": 48,
          "count": 1,
          "perMonth": 7,
          "perWeek": 2,
          "perDay": 0.2
        },
        {
          "name": "Continental Scp",
          "domain": null,
          "total": 40,
          "count": 2,
          "perMonth": 6,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "Bj Aribau 92",
          "domain": null,
          "total": 34,
          "count": 1,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "Merpago Lameccafit",
          "domain": null,
          "total": 32,
          "count": 1,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "2006",
          "domain": null,
          "total": 29,
          "count": 2,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Taulat 44",
          "domain": null,
          "total": 27,
          "count": 2,
          "perMonth": 4,
          "perWeek": 1,
          "perDay": 0.1
        }
      ],
      "extra": {
        "count": 58,
        "perMonth": 93
      }
    },
    {
      "key": "groceries",
      "label": "Groceries",
      "total": 734,
      "count": 52,
      "perMonth": 112,
      "perWeek": 26,
      "perDay": 3.7,
      "deductible": 0,
      "business": false,
      "spark": [
        0.7790911625313633,
        0.9660440479509339,
        0.923557290214664,
        1,
        0,
        0.3977697240033454,
        0.027042096459436855
      ],
      "monthly": [
        140,
        173,
        166,
        179,
        0,
        71,
        5
      ],
      "merchants": [
        {
          "name": "Bonpreu",
          "domain": "bonpreu.cat",
          "total": 397,
          "count": 12,
          "perMonth": 61,
          "perWeek": 14,
          "perDay": 2
        },
        {
          "name": "Condis",
          "domain": "condis.es",
          "total": 67,
          "count": 8,
          "perMonth": 10,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Sainsbury's",
          "domain": null,
          "total": 33,
          "count": 5,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "Supermarket",
          "domain": null,
          "total": 32,
          "count": 2,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "Marks & Spencer",
          "domain": null,
          "total": 31,
          "count": 3,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "Picardia",
          "domain": null,
          "total": 30,
          "count": 1,
          "perMonth": 5,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Supermercat Baga",
          "domain": null,
          "total": 26,
          "count": 1,
          "perMonth": 4,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Ametller Origen",
          "domain": null,
          "total": 24,
          "count": 2,
          "perMonth": 4,
          "perWeek": 1,
          "perDay": 0.1
        }
      ],
      "extra": {
        "count": 14,
        "perMonth": 12
      }
    },
    {
      "key": "subscriptions",
      "label": "Subscriptions",
      "total": 498,
      "count": 29,
      "perMonth": 76,
      "perWeek": 18,
      "perDay": 2.5,
      "deductible": 0,
      "business": false,
      "spark": [
        0.3564492993490014,
        0.867041818382434,
        1,
        0.1617014233697451,
        0.14327485380116958,
        0.14327485380116958,
        0.07718194858214718
      ],
      "monthly": [
        65,
        157,
        181,
        29,
        26,
        26,
        14
      ],
      "merchants": [
        {
          "name": "Pastdue Credit",
          "domain": null,
          "total": 114,
          "count": 1,
          "perMonth": 17,
          "perWeek": 4,
          "perDay": 0.6
        },
        {
          "name": "Www.assurantsoluti",
          "domain": null,
          "total": 104,
          "count": 1,
          "perMonth": 16,
          "perWeek": 4,
          "perDay": 0.5
        },
        {
          "name": "Youtube",
          "domain": null,
          "total": 102,
          "count": 8,
          "perMonth": 16,
          "perWeek": 4,
          "perDay": 0.5
        },
        {
          "name": "Amazon Prime",
          "domain": "amazon.com",
          "total": 56,
          "count": 8,
          "perMonth": 9,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Metal Plan Fee",
          "domain": null,
          "total": 52,
          "count": 3,
          "perMonth": 8,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Netflix",
          "domain": "netflix.com",
          "total": 42,
          "count": 6,
          "perMonth": 6,
          "perWeek": 1,
          "perDay": 0.2
        },
        {
          "name": "Spotify",
          "domain": "spotify.com",
          "total": 29,
          "count": 2,
          "perMonth": 4,
          "perWeek": 1,
          "perDay": 0.1
        }
      ]
    },
    {
      "key": "transport",
      "label": "Transport",
      "total": 477,
      "count": 59,
      "perMonth": 73,
      "perWeek": 17,
      "perDay": 2.4,
      "deductible": 0,
      "business": false,
      "spark": [
        0.36706798225762655,
        0.34063546664252736,
        1,
        0.24988684710781214,
        0.06952113696026072,
        0.06798225762650494,
        0.06336561962523762
      ],
      "monthly": [
        81,
        75,
        221,
        55,
        15,
        15,
        14
      ],
      "merchants": [
        {
          "name": "Uber",
          "domain": "uber.com",
          "total": 168,
          "count": 32,
          "perMonth": 26,
          "perWeek": 6,
          "perDay": 0.8
        },
        {
          "name": "Tmb",
          "domain": null,
          "total": 68,
          "count": 5,
          "perMonth": 10,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Free Now",
          "domain": "free-now.com",
          "total": 58,
          "count": 4,
          "perMonth": 9,
          "perWeek": 2,
          "perDay": 0.3
        },
        {
          "name": "Greater Anglia",
          "domain": null,
          "total": 50,
          "count": 2,
          "perMonth": 8,
          "perWeek": 2,
          "perDay": 0.2
        },
        {
          "name": "Transport For London",
          "domain": null,
          "total": 22,
          "count": 4,
          "perMonth": 3,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Llic 10129",
          "domain": null,
          "total": 15,
          "count": 1,
          "perMonth": 2,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Licencia N 9332",
          "domain": null,
          "total": 14,
          "count": 1,
          "perMonth": 2,
          "perWeek": 0,
          "perDay": 0.1
        },
        {
          "name": "Ferrocarrils De La Generalitat Catalunya",
          "domain": null,
          "total": 14,
          "count": 1,
          "perMonth": 2,
          "perWeek": 0,
          "perDay": 0.1
        }
      ],
      "extra": {
        "count": 9,
        "perMonth": 11
      }
    },
    {
      "key": "health_fitness",
      "label": "Health & fitness",
      "total": 376,
      "count": 13,
      "perMonth": 58,
      "perWeek": 13,
      "perDay": 1.9,
      "deductible": 0,
      "business": false,
      "spark": [
        0.9061455907664271,
        0.7087172218284905,
        1,
        0.20147818163409942,
        0.35435861091424525,
        0.6378454996456414,
        0
      ],
      "monthly": [
        90,
        70,
        99,
        20,
        35,
        63,
        0
      ],
      "merchants": [
        {
          "name": "Classpass",
          "domain": "classpass.com",
          "total": 175,
          "count": 5,
          "perMonth": 27,
          "perWeek": 6,
          "perDay": 0.9
        },
        {
          "name": "Sundy Unisex Hair Salo",
          "domain": null,
          "total": 105,
          "count": 3,
          "perMonth": 16,
          "perWeek": 4,
          "perDay": 0.5
        },
        {
          "name": "Puregym",
          "domain": null,
          "total": 29,
          "count": 1,
          "perMonth": 4,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Bless Barber Shop",
          "domain": null,
          "total": 28,
          "count": 1,
          "perMonth": 4,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Why Not Barbershop",
          "domain": null,
          "total": 20,
          "count": 1,
          "perMonth": 3,
          "perWeek": 1,
          "perDay": 0.1
        },
        {
          "name": "Ink And Needles",
          "domain": null,
          "total": 20,
          "count": 2,
          "perMonth": 3,
          "perWeek": 1,
          "perDay": 0.1
        }
      ]
    }
  ]
};
